In [1]:
import numpy as np

s = np.array([1,2,3,4])
s1 = np.array([1,2,3,4], ndmin = 2)
s1

array([[1, 2, 3, 4]])

In [4]:
s2 = np.array([1,2,3,4], dtype = complex)
s2

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [8]:
x = np.dtype(np.int32)
x
x1 = np.dtype('i2') # i1 = int8, i2 = int16, i3 = int32
x1

dtype('int16')

In [13]:
age = np.dtype([('age', 'i1')])
age
a = np.array([(10,),(20,),(30,)], dtype = age)
a

array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [14]:
a['age']

array([10, 20, 30], dtype=int8)

In [17]:
student = np.dtype([('name','S20'),('age','i1'),('mark','f2')])
student

dtype([('name', 'S20'), ('age', 'i1'), ('mark', '<f2')])

In [18]:
student['name']


dtype('S20')

In [19]:
a.shape

(3,)

In [21]:
b = np.array([[1,2,3,4],[5,6,7,8]])
c = b.reshape(4,2)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
k = np.arange(24)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
d = k.reshape(2,4,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [30]:
a = np.array([1,2,3,4])
a.itemsize # Array datatype size not array size

4

In [32]:
a = np.array([3,2])
a
a = np.empty([3,2])
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
a = np.empty([3,2], dtype = int)
a # Random values

array([[305248064,       587],
       [        0,         0],
       [   131074,   2978304]])

In [35]:
v = np.zeros([3,2])
u = np.ones([3,2])
v
u

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
x = [1,2,3,4,5]
a = np.asarray(x)
a

array([1, 2, 3, 4, 5])

In [37]:
a = np.asarray(x, dtype = float)
a

array([1., 2., 3., 4., 5.])

In [38]:
a = np.asarray(x, dtype = tuple)
a

array([1, 2, 3, 4, 5], dtype=object)

In [39]:
a = np.arange(1, 50, 10, dtype = int)
a

array([ 1, 11, 21, 31, 41])

In [40]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
s = slice(3, 8, 2)
s

slice(3, 8, 2)

In [43]:
c = a[1:5:2]
c

array([3, 7])

In [44]:
a[3:7]

array([ 7,  9, 11, 13])

In [47]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]] # [0,0], [1,1], [2,0] index numbers
y

array([1, 4, 5])

In [48]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
x[x > 5]

array([ 6,  7,  8,  9, 10, 11])

In [50]:
# Broadcasting

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

a+b


array([11, 22, 33, 44])

In [54]:
# Broadcasting
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])

a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [55]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
for x in np.nditer(a):
    print(x)

1
2
3
4
5
6
7
8
9
